### PR TITLE
Bug sweep

### LINKED ISSUE #11: Handle search paths better
This situation will not be handled correctly:

**jasmine.json**

``` json
{
  "spec_files": [ "path1", "path2" ]
}
```

**path1/test.js**

``` js
describe('A suite', function () {});
```

**path2/test.js**

``` js
describe('Another suite', function () {});
```

In this case, only "A suite" gets run and not "Another suite" because `path1` and `path2` are both added to `imports.searchPath`. When Jasmine goes to import `test` twice, then `path1/test.js` fulfills the requirement both times.

### LINKED ISSUE #13: Error message is unhelpful when suite import fails
If you have a test suite that can't be imported, for example because of a syntax error, then the error message you get is quite unhelpful:

```
Exception occurred inside Jasmine:
SyntaxError: syntax error
Jasmine<.loadSpecs/<@/path/to/jasmine-gjs/jasmineBoot.js:119
Jasmine<.loadSpecs@/path/to/jasmine-gjs/jasmineBoot.js:115
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
Jasmine<.execute@/path/to/jasmine-gjs/jasmineBoot.js:128
wrapper@resource:///org/gnome/gjs/modules/lang.js:178
run/<@/path/to/jasmine-gjs/command.js:227
run@resource:///org/gnome/gjs/modules/mainloop.js:33
run@/path/to/jasmine-gjs/command.js:243
@/path/to/jasmine:50
```

Notice that it doesn't tell you which file the syntax error is in; the error is thrown from the import statement. This should produce a better error message which tells you which file failed to import, and ideally even continues with the rest of the test suites while registering a failure for the problematic one.

### LINKED ISSUE #14: Should support passing different executable to jasmine-runner subprocess
Gnome Shell, for example, needs to run its JS tests with a custom executable that links certain libraries before calling into GJS. See: https://github.com/GNOME/gnome-shell/blob/master/src/run-js-test.c

This currently isn't supported by our jasmine-runner setup.

### LINKED ISSUE #16: Should be able to run Jasmine under GDB
Launching the actual tests in a subprocess currently interferes with running tests under GDB.

### LINKED ISSUE #26: Should fail if nonexistent file passed on command line
`jasmine glhjgflhjlfjhldf.js` outputs this:
```
Started


No specs found

Finished in 0 s
```
and exits with code 0.

This can mask an error in your build system if you are passing the wrong files to Jasmine. It should print that one or more files given on the command line were not found, and exit with an error code.

### PR DESCRIPTION
**Pull request by ptomato**
Closes: #11
Closes: #13
Closes: #14 
Closes: #16
Closes: #26

### CODE REVIEW

File: src/config.js [hunk 1]
```diff
@@ -116,4 +117,19 @@ function prepareLauncher(launcher, config) {
                 launcher.setenv(key, config.environment[key], true);
         });
     }
+    if (options.debug)
+        launcher.flags |= Gio.SubprocessFlags.STDIN_INHERIT;
```
Comment (andyholmes) [inline src/config.js]: It's odd because the self-tests pass, but I get this error when running with `--debug`:

```
g_object_set_is_valid_property: construct property "flags" for object 'GSubprocessLauncher' can't be set after construction
```
Maybe `prepareLanucher()` should just return the `GSubprocessLauncher`?

Comment (ptomato) [reply src/config.js]: I neglected to test this one last time before making the change. It's super bizarre; `flags` is construct-only but nonetheless there is a [`set_flags()`](https://gjs-docs.gnome.org/gio20~2.64p/gio.subprocesslauncher#method-set_flags) method.

(The self-test passes because we use a mock object for the launcher.)

Comment (andyholmes) [reply src/config.js]: Ah I see that now, it's actually `write/construct-only` (even stranger) so I'm not sure re-reading the flags after the fact will work either.
